### ISSUE TITLE
Error when building my project...

### ISSUE THREAD

**Issue by r3id** [arcage/crystal-quotedprintable#2]
I am getting the following error

```
Error in quoted_printable:shard.yml: mapping values are not allowed in this context at line 7, column 17

  5.   - ʕ·ᴥ·ʔAKJ <arcage@denchu.org>
  6.
  7. crystal: crystal: ">= 0.27.0, < 2.0.0"
 ```

Looks like you have crystal replicated twice.

**Comment by arcage** [comment]
Thank you for your comment.

I will fix it soon.

**Comment by arcage** [comment]
I have released v0.1.3 to fix this issue.

But, It seems that there are some cases the unsolved version will be fetched when the dependency setting in shard.yml without specifying version. 

If you face that case, please try to add `version: ">= 0.1.3"` to dependency part of this shard in your `shard.yml`.

```yaml
dependencies:
  quoted_printable:
    github: arcage/crystal-quotedprintable
    version: ">= 0.1.3"
```
